[application]
name = "rentity-dioxus-example"
default_platform = "web"

[web.app]
title = "rentity Dioxus Example"

[web.watcher]
watch_path = ["src", "../../crates/hyle/src", "../../crates/hyle-dioxus/src", "../../crates/hyle-dioxus-native/src"]
reload_html = true
